### ISSUE TITLE
Group prompt can be skipped

### ISSUE THREAD

**Issue by nethvish** [pawan-live/lecture-timetable-app#1]
Displays as null
![Bug](https://user-images.githubusercontent.com/92233131/152691746-81ead82e-e54b-409c-8230-c105229b69b7.jpg)

**Comment by pawan-live** [comment]
Thanks for the contribution. Will address soon

**Comment by pawan-live** [comment]
The js prompt won't be required with the new in-page login prompt. Btw thanks @IT21310478
