### ISSUE TITLE
Button is not working id=submit-btn

### ISSUE THREAD

**Issue by pawan-live** [pawan-live/lecture-timetable-app#12]
#11 @it21310478

**Comment by nethvish** [comment]
will fix it tomorrow

**Comment by pawan-live** [comment]
@IT21310478 any progress?

**Comment by pawan-live** [comment]
Also I have reverted the code back to previous state (just before the merge)

**Comment by pawan-live** [comment]
Now that the code has been restored to the previous version, this issue doesn't exist.
